batch_size: 16
checkpoint_dir: results/diffusion
config: config.yml
device: cuda:0
fov: 10
image_size: 64
keep_num_checkpoint: 10
lam_flip: 0.5
lam_perc: 1
lam_reg: 0.001
load_gt_depth: false
log_freq: 1000
lr: 0.0001
max_depth: 1.1
min_depth: 0.9
model_name: unsup3d_diffusion
num_epochs: 60
num_workers: 4
resume: true
rot_center_depth: 1.0
run_train: true
save_checkpoint_freq: 1
seed: 1234
tex_cube_size: 2
train_val_data_dir: /home/user2/dataset/face/VoxCeleb/unzippedFaces
use_logger: true
weight_albedo: 1
weight_depth: 1
xy_translation_range: 0.1
xyz_rotation_range: 60
z_translation_range: 0
