## model
model_name: unsup3d_celeba
min_depth: 0.9
max_depth: 1.1
xyz_rotation_range: 60  # (-r,r) in degrees
xy_translation_range: 0.1  # (-t,t) in 3D
z_translation_range: 0  # (-t,t) in 3D
lam_perc: 1
lam_flip: 0.5
lr: 0.0001
